FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    pandas numpy sqlalchemy psycopg2-binary streamlit plotly

COPY src/ ./src/
COPY data/ ./data/

EXPOSE 8501

CMD ["streamlit", "run", "src/dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
